---
title: "Week 4 Homework"
author: "Nooriza Maharani"
date: "2024-10-25"
output:
  html_document: 
    theme : cerulean

---

#### 1. Load the needed library 
```{r}
library(easypackages)
libraries("countrycode", "dplyr", "tidyverse", "sf","tmap")
```


#### 2. Load the CSV data: World GII Composite Data
```{r}
composit <- read_csv("https://hdr.undp.org/sites/default/files/2023-24_HDR/HDR23-24_Composite_indices_complete_time_series.csv",
                       locale = locale(encoding = "latin1"),
                       na = "n/a")
```


#### 3. Dealing with CSV data
```{r}
#selecting columns using contains
data_2years <- composit %>%  dplyr::select(
  contains("iso3"),
  contains("country"),
  contains("gii_2010"),
  contains("gii_2019"))


#Delete unnecessary columns 
data_3years <- data_2years[-206,] #world
cleaned_csv <- data_3years[-c(196:205),] #unnecessary column


#Create new column : difference  and categorical column for the result
world_gii <- cleaned_csv %>%
  mutate(difference = (gii_2019-gii_2010)) %>%
  mutate(compare = case_when(difference >= 0 ~ "Index Increasing",
                             difference < 0 ~ "Index Decreasing",
                             TRUE ~ as.character(NA)))


# Making "NA" appears as a label in the legend
world_gii <- world_gii %>%
  mutate(compare = ifelse(is.na(compare), "NA", compare))
```


#### 4. Load Geojson file
```{r}
world_json <- st_read("World_Countries_(Generalized)_9029012925078512962.geojson")
```


#### 5. Dealing with JSON data: World Countries
```{r}
#Creating iso3
world_json2 <- world_json %>%
mutate(iso3_code = countrycode(COUNTRY, "country.name", "iso3c"))
```


#### 6. Join JSON and CSV
```{r}
world_gii_joined <- world_json2 %>% 
  merge(.,
        world_gii,
        by.x = 'iso3_code',
        by.y = 'iso3',
        no.dups = TRUE) %>% 
  distinct() 


###Delete unnecessary columns after join
world_gii_joined2 <- world_gii_joined[,-c(2:6)]
```


#### 7. Viz : Creating a map
```{r}
tmap_mode("plot")


tm_shape(world_gii_joined2) + 
tm_fill("compare", title = "Legend")+
tm_borders()+
tm_layout(main.title = "World Gender Inequality Index (2019-2010)",
          main.title.size = 1,  # Title size
          main.title.position = c("center", "top"),
          legend.text.size = 0.5,
          legend.title.size = 0.5,
          legend.position = c("left", "bottom"))
```



#### 8. Viz : Creating interactive map
```{r}
library(leafpop)
library(leaflet)

popupgii <- world_gii_joined2 %>%
  st_drop_geometry()%>%
  dplyr::select(difference, COUNTRY)%>%
  popupTable()

tmap_mode("view")

breaks = c(-0.1, -0.05, 0, 0.05, 0.1, 0.15, 0.5)

pal_gii<-world_gii_joined2%>%
  colorBin(palette = "PuBu", domain=.$difference, bins = breaks)

map <- leaflet(world_gii_joined2) %>%
  addPolygons(color="white",
              weight = 2,
              opacity = 1,
              popup = popupgii,
              fillOpacity = 0.7,
              fillColor = ~pal_gii(difference),
              group = "GII")%>%
  addTiles(group = "OSM (default)") %>%
  addProviderTiles(providers$CartoDB.Positron, group = "CartoDB")%>%
  addLegend(pal = pal_gii, values = ~difference, position ="bottomleft", title = "Gender inequality index") %>%
  addLayersControl(
    baseGroups = c("OSM (default)", "CartoDB"),
    overlayGroups = c("GII"),
    options = layersControlOptions(collapsed = FALSE)
  )
map
 

```



